### ISSUE TITLE
出现未知错误

### ISSUE THREAD

**Issue by nicolas23333** [xz454867105/fxxk_chaoxing#10]
![954844fb33a7e7c4fc2b02d6f4a3516](https://user-images.githubusercontent.com/32031250/132294572-3d9b9e1b-5517-4481-a348-3b399d728ac7.png)

**Comment by nicolas23333** [comment]
未知问题如上图。另外，如果我选择的课程是已经全部看完的课程，是可以正常加载视频文件的。
给您麻烦了，谢谢！

**Comment by xz454867105** [comment]
你好 我修改了一段报错显示的代码，麻烦你再试试吧，如果还是报错了麻烦再截个图，谢谢

**Comment by nicolas23333** [comment]
已经基本无问题，只是在“在xxxxx章节中找到0个任务点”之后会出现若干个“错误类型:KeyError
错误明细:'data'
错误类型:KeyError
错误明细:'data'
错误类型:KeyError
错误明细:'data'
错误类型:KeyError
错误明细:'data'
错误类型:KeyError
错误明细:'data'
错误类型:KeyError
错误明细:'data'
错误类型:KeyError
错误明细:'data'
错误类型:KeyError
错误明细:'data'
错误类型:KeyError
错误明细:'data'
错误类型:KeyError
错误明细:'data'
错误类型:KeyError”的信息，但并不影响使用。

**Comment by xz454867105** [comment]
应该是有一种任务点这段代码识别不了，因为我写这段代码的时候只考虑到我见过的任务点，有些我没见过的也就不知道怎么识别出来。

**Comment by nicolas23333** [comment]
是的，我看了一下我这个课程的任务点除了视频的还有章节测验的。如果你后续需要开发这部分功能的话我可以把我的账号密码提供给你。
