### ISSUE TITLE
任务点加载不全的问题

### ISSUE THREAD

**Issue by nicolas23333** [xz454867105/fxxk_chaoxing#11]
我的一门课程任务点（全部是视频）有143个，但程序加载出的任务点只有前92个，之后的加载不出来。
另一门课程的视频任务点有189个，但程序加载出的任务点只有前120个，之后的加载不出来。
重复尝试多次，发现每次都是能加载的任务点数量固定不变。

**Comment by xz454867105** [comment]
和上一个issue里的问题类似，经过这一段时间的使用反馈，学习通里的视频任务点好像也不止一种，所以会出现识别不出来任务点的情况

**Comment by nicolas23333** [comment]
应该不是，我这边没有被加载的任务点和加载出的任务点是一样的，都是视频

**Comment by nicolas23333** [comment]
抱歉我没有看到你说的“视频任务点也不止一种”，我重新看了一下，我所说的这个问题中只能加载出前92个任务点的课程，加载完92个任务点后，没有像上一个问题所述的一样打出“错误明细:'data'错误类型:KeyError”，说明未加载的任务点可能不一定是因为识别不出来，可能另有原因。

**Comment by nicolas23333** [comment]
抱歉我昨天没注意到你说的“视频任务点也不止一种”。我重新看了一下，我所说的这个问题中只能加载出前92个任务点的课程，加载完92个任务点后（全部都是连续的），没有像上一个问题所述的一样打出“错误明细:'data'错误类型:KeyError”，说明未加载的任务点可能不一定是因为识别不出来，可能另有原因。

**Comment by xz454867105** [comment]
可能是的，但是由于我近期时间不多，所以这个应该是不会做大更新，等以后有时间了再修改。现在就只能勉强完成前面这部分的内容了，不好意思。
