### ISSUE TITLE
选了课错误

### ISSUE THREAD

**Issue by obito-ei** [xz454867105/fxxk_chaoxing#12]
![1631185943(1)](https://user-images.githubusercontent.com/63336576/132675916-f1c53b50-f163-48b5-9434-f7d22f8c9191.png)

**Comment by xz454867105** [comment]
这个报错的问题在于你的网络。
你可以检查一下你的网络连接是否正常
你的代理有没有正确的配置。

**Comment by obito-ei** [comment]
可以了，这个如果想一个账号多选科目 该怎么输入编号

**Comment by xz454867105** [comment]
在每次启动程序的时候都会要求选择课程，如果要选新课程，直接输入序号选择即可。程序不能实现多课程直接切换。
