### ISSUE TITLE
没有运行过其他程序的菜鸟安装Requests才能使用

### ISSUE THREAD

**Issue by iodjjd** [xz454867105/fxxk_chaoxing#14]
作者您好，如果是一个新手玩家第一次运行这个python脚本可能会报错，需要运行 `python -m pip install requests` 这行命令才能运行程序，如果是个老手已经弄了其他的脚本没有这个问题，因为已经安装了

**Comment by xz454867105** [comment]
我会在readme里加入提示内容，谢谢提醒。
