### ISSUE TITLE
[BUG反馈]  执行pip install -r requirements安装相关依赖又出错

### ISSUE THREAD

**Issue by iodjjd** [xz454867105/fxxk_chaoxing#16]
**形容Bug的信息**
**************\fxxk_chaoxing-main>pip install -r requirements
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements'

**Screenshots**
![image](https://user-images.githubusercontent.com/76802920/133947471-5b484c7c-cf88-41a9-b185-3809d2e75c84.png)

**运行环境 (请完善以下信息):**
 - 系统：win10 1903
 - Python环境版本: python3.9.7
 - 运行方式: 源代码运行

**其他内容**
您觉得对问题反馈有帮助的内容

**Comment by xz454867105** [comment]
不好意思是我没写清楚
pip install -r requirements.txt
