### ISSUE TITLE
选择课程后报错

### ISSUE THREAD

**Issue by BaoBaoss** [xz454867105/fxxk_chaoxing#18]
**形容Bug的信息**
输入课程序号后出现报错，报错前一行日志：正在尝试在线读取课程记录
**Screenshots**
![image](https://user-images.githubusercontent.com/45710021/134447204-fe7e8938-aaf8-4557-843a-75afbf817a17.png)
![image](https://user-images.githubusercontent.com/45710021/134447233-102baa49-ffde-412c-beb1-2d4f830d8429.png)

**运行环境 (请完善以下信息):**
 - 系统：Windows10
 - Python环境版本:Python3.6
 - 运行方式: 源代码运行

**其他内容**
您觉得对问题反馈有帮助的内容

**Comment by xz454867105** [comment]
检查你的代理连接是否正常，检查你的网络是否稳定
这个SSL protocol的报错大多数都是你网络的问题

**Comment by xz454867105** [comment]
最新的urllib3库对HTTPS的代理支持有问题，最好的建议就是不要走代理。假如不想关闭代理，可以尝试将urllib3库降级至1.25及以下，这个版本的urllib3还是支持的
