### ISSUE TITLE
[BUG反馈]当课程节点大于120时无法爬取

### ISSUE THREAD

**Issue by qq2540040142** [xz454867105/fxxk_chaoxing#19]
爬取速度太快且课程节点大于120会出现输入验证码的情况
Json格式错误了所以就报错    JSONDecodeErrorExpecting value: line 1 column 1 (char 0)
建议对爬取速度延时处理,具体延时多少暂未测试,我这里延时3s
如果您有更好的方法请加以改进
**Screenshots**

![屏幕截图 2021-10-01 232829](https://user-images.githubusercontent.com/56993378/135647008-b7fbe5dd-7b10-4f07-a170-226713a155be.png)

**Comment by xz454867105** [comment]
你可以尝试一下在出现验证码后
1)重置session
2)延时尝试(仅在检测到验证码后再延时)
每次爬取都延时一次效率的太低了

**Comment by qq2540040142** [comment]
OK
