### ISSUE TITLE
集成进APP

### ISSUE THREAD

**Issue by qq2540040142** [xz454867105/fxxk_chaoxing#20]
作者你好,我将您的代码集成于APP内,并且注明python来自于您,想要开源到github,不知是否可以

**Comment by qq2540040142** [comment]
![1](https://user-images.githubusercontent.com/56993378/135848085-bc58e3f5-fb98-4db8-b0ac-02c46958fd9f.jpg)
![2](https://user-images.githubusercontent.com/56993378/135848108-8b8bf7c0-db03-417f-8c30-50131a1ee2d4.jpg)
![3](https://user-images.githubusercontent.com/56993378/135848114-e113cae1-afb8-4bd1-8119-33c466a425e3.jpg)

**Comment by xz454867105** [comment]
可以的，只要开源就可以
