### ISSUE TITLE
代码有问题

### ISSUE THREAD

**Issue by wangdi376** [xz454867105/fxxk_chaoxing#3]
data以后有问题，可能超星网站升级了，建议作者更新一下。

**Comment by wangdi376** [comment]
`Traceback (most recent call last):
  File ".\best.py", line 103, in prework
    f = open(os.path.join(str(self.usernm),str(course['courseid']),'job_list.json'),'r')
FileNotFoundError: [Errno 2] No such file or directory: 'job_list.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\best.py", line 497, in <module>
    a.main()
  File ".\best.py", line 491, in main
    self.prework()
  File ".\best.py", line 117, in prework
    self.find_objects(item, course['courseid'])
  File ".\best.py", line 196, in find_objects
    content = str(json.loads(req.text)['data'][0]['card']['data']).replace('&quot;', '')
KeyError: 'data'`

**Comment by xz454867105** [comment]
收到，刚刚检查发现是超星网更新了，有些任务点的识别方法改变了，我计划开学之后再改出来，等我发出来了再关掉这个issue

**Comment by wangdi376** [comment]
啊这，我想着假期我们在腾讯会议，超星还有课，希望作者大大有空更新下(⸝⸝•‧̫•⸝⸝)

**Comment by wangdi376** [comment]
作者大大更新了吗

**Comment by xz454867105** [comment]
已经更新好了 你看看能用了不

**Comment by wangdi376** [comment]
行我测试一下先------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年3月23日(星期二) 上午10:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xz454867105/fxxk_chaoxing] 代码有问题 (#3)

**Comment by wangdi376** [comment]
多版本的也更新了吗，单版本的可以用。------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年3月23日(星期二) 上午10:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xz454867105/fxxk_chaoxing] 代码有问题 (#3)
