### ISSUE TITLE
运行时有问题

### ISSUE THREAD

**Issue by nicolas23333** [xz454867105/fxxk_chaoxing#7]
sophia@SophiadeMacBook-Pro fxxk_chaoxing-main % python best.py
  File "best.py", line 55
SyntaxError: Non-ASCII character '\xe6' in file best.py on line 55, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by xz454867105** [comment]
你需要在best.py文件的最上面加上# encoding: utf-8
