### ISSUE TITLE
出现未知错误

### ISSUE THREAD

**Issue by Hentai02** [xz454867105/fxxk_chaoxing#9]
![QQ图片20210905124247.jpg](https://i.loli.net/2021/09/05/2XjsT8aMcE9PoFS.jpg)

**Comment by xz454867105** [comment]
如果是用的conda，建议你新建个python3.6的环境，3.8和3.9版本太高了，经常会出现各种库缺少的问题。

**Comment by Hentai02** [comment]
装完发现不支持![Snipaste_2021-09-05_19-02-02.png](https://i.loli.net/2021/09/05/9SuTKgWH1DGrmYQ.png)

**Comment by xz454867105** [comment]
如果愿意的话，可以麻烦你把你的账号密码发给我检查一下代码吗。邮箱地址：csk@samuelchen.cn

**Comment by Hentai02** [comment]
代码是直接克隆你的，电脑上能用，就是在termux上用不了

**Comment by Hentai02** [comment]
不过电脑上是python3.6.x

**Comment by xz454867105** [comment]
在电脑上运行正常是吧

**Comment by xz454867105** [comment]
我代码没有对Linux和macOS做适配，可能这也是个问题

**Comment by Hentai02** [comment]
大佬，有时间还是适配一下吧，电脑不能24小时运行

**Comment by Hentai02** [comment]
检测不到三个选项卡的视频任务
![Snipaste_2021-09-21_17-37-15.png](https://i.loli.net/2021/09/21/Boha9ucjxOAelQL.png)
![QQ图片20210921175129.jpg](https://i.loli.net/2021/09/21/Q619miRbTHhZBUA.jpg)
